# Generated by Django 3.1.3 on 2020-11-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('idLocal', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('direccionLocal', models.CharField(max_length=100)),
                ('encargadoLocal', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('idProduccion', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('horaInicio', models.IntegerField()),
                ('fechaFinal', models.DateField()),
                ('horaTermino', models.IntegerField()),
                ('lugarEvento', models.CharField(max_length=30)),
                ('invitados', models.IntegerField()),
                ('seguridad', models.IntegerField()),
                ('dj', models.IntegerField()),
                ('bartender', models.IntegerField()),
            ],
        ),
    ]
